"""GitHub リポジトリトピック → スキルのマッピング定義。"""

from typing import Dict, List

# GitHubリポジトリのトピック → スキル一覧
TOPIC_TO_SKILLS: Dict[str, List[str]] = {
    # フレームワーク
    "react": ["React"],
    "reactjs": ["React"],
    "vue": ["Vue"],
    "vuejs": ["Vue"],
    "angular": ["Angular"],
    "svelte": ["Svelte"],
    "nextjs": ["Next.js"],
    "next-js": ["Next.js"],
    "nuxt": ["Nuxt.js"],
    "nuxtjs": ["Nuxt.js"],
    "astro": ["Astro"],
    "gatsby": ["Gatsby"],
    "remix": ["Remix"],
    "fastapi": ["FastAPI"],
    "django": ["Django"],
    "flask": ["Flask"],
    "express": ["Express"],
    "expressjs": ["Express"],
    "nestjs": ["NestJS"],
    "spring-boot": ["Spring Boot"],
    "spring": ["Spring Boot"],
    "rails": ["Rails"],
    "ruby-on-rails": ["Rails"],
    "laravel": ["Laravel"],
    "gin": ["Gin"],
    "actix": ["Actix"],
    "phoenix": ["Phoenix"],
    "aspnet": ["ASP.NET"],
    # モバイル
    "react-native": ["React Native"],
    "flutter": ["Flutter"],
    "swiftui": ["SwiftUI"],
    "jetpack-compose": ["Jetpack Compose"],
    "ionic": ["Ionic"],
    # データベース
    "postgresql": ["PostgreSQL"],
    "postgres": ["PostgreSQL"],
    "mysql": ["MySQL"],
    "mongodb": ["MongoDB"],
    "redis": ["Redis"],
    "sqlite": ["SQLite"],
    "dynamodb": ["DynamoDB"],
    "elasticsearch": ["Elasticsearch"],
    "neo4j": ["Neo4j"],
    "firebase": ["Firebase"],
    # インフラ
    "docker": ["Docker"],
    "kubernetes": ["Kubernetes"],
    "k8s": ["Kubernetes"],
    "terraform": ["Terraform"],
    "pulumi": ["Pulumi"],
    "ansible": ["Ansible"],
    "helm": ["Helm"],
    "cloudformation": ["CloudFormation"],
    # クラウド
    "aws": ["AWS"],
    "gcp": ["GCP"],
    "google-cloud": ["GCP"],
    "azure": ["Azure"],
    # CI/CD
    "github-actions": ["GitHub Actions"],
    "gitlab-ci": ["GitLab CI"],
    "jenkins": ["Jenkins"],
    "circleci": ["CircleCI"],
    "argocd": ["ArgoCD"],
    # モニタリング
    "prometheus": ["Prometheus"],
    "grafana": ["Grafana"],
    "datadog": ["Datadog"],
    "sentry": ["Sentry"],
    "opentelemetry": ["OpenTelemetry"],
    # 機械学習 / データ
    "tensorflow": ["TensorFlow"],
    "pytorch": ["PyTorch"],
    "scikit-learn": ["scikit-learn"],
    "sklearn": ["scikit-learn"],
    "huggingface": ["Hugging Face"],
    "langchain": ["LangChain"],
    "mlflow": ["MLflow"],
    "pandas": ["Pandas"],
    "numpy": ["NumPy"],
    "machine-learning": ["scikit-learn"],
    "deep-learning": ["PyTorch"],
    "spark": ["Apache Spark"],
    "apache-spark": ["Apache Spark"],
    "kafka": ["Apache Kafka"],
    "apache-kafka": ["Apache Kafka"],
    "airflow": ["Airflow"],
    "dbt": ["dbt"],
    "bigquery": ["BigQuery"],
    "snowflake": ["Snowflake"],
    # その他
    "graphql": ["GraphQL"],
    "grpc": ["gRPC"],
    "rest-api": ["REST API"],
    "websocket": ["WebSocket"],
    "nginx": ["Nginx"],
    "linux": ["Linux"],
}
