"""マスタデータの初期シードを投入するモジュール。"""

from sqlalchemy.orm import Session

from ..repositories import (
    MQualificationRepository,
    MTechnologyStackRepository,
)

# 資格マスタ
_QUALIFICATIONS = [
    {"name": "ITストラテジスト（ST）", "sort_order": 1},
    {"name": "システム監査技術者（AU）", "sort_order": 2},
    {"name": "プロジェクトマネージャ（PM）", "sort_order": 3},
    {"name": "システムアーキテクト（SA）", "sort_order": 4},
    {"name": "ITサービスマネージャ（SM）", "sort_order": 5},
    {"name": "ネットワークスペシャリスト（NW）", "sort_order": 6},
    {"name": "データベーススペシャリスト（DB）", "sort_order": 7},
    {"name": "エンベデッドシステムスペシャリスト（ES）", "sort_order": 8},
    {"name": "情報処理安全確保支援士試験（SC）", "sort_order": 9},
    {"name": "応用情報技術者試験（AP）", "sort_order": 10},
    {"name": "基本情報処理技術者（FE）", "sort_order": 11},
    {"name": "ITパスポート試験", "sort_order": 12},
    {"name": "情報セキュリティマネジメント試験", "sort_order": 13},
    {"name": "ウェブデザイン技能検定 1級", "sort_order": 14},
    {"name": "ウェブデザイン技能検定 2級", "sort_order": 15},
    {"name": "ウェブデザイン技能検定 3級", "sort_order": 16},
    {"name": "第1種衛生管理者", "sort_order": 17},
    {"name": "第2種衛生管理者", "sort_order": 18},
    {"name": "Certified Kubernetes Application Developer（CKAD）", "sort_order": 19},
    {"name": "Certified Kubernetes Administrator (CKA)", "sort_order": 20},
    {"name": "Google Cloud認定資格 Cloud Digital Leader", "sort_order": 21},
    {"name": "Google Cloud認定資格 Associate Cloud Engineer", "sort_order": 22},
    {"name": "Google Cloud認定資格 Professional Cloud Architects", "sort_order": 23},
    {"name": "Google Cloud認定資格 Professional Cloud Database Engineer", "sort_order": 24},
    {"name": "Google Cloud認定資格 Professional Cloud Developer", "sort_order": 25},
    {"name": "Google Cloud認定資格 Professional Data Engineer", "sort_order": 26},
    {"name": "Google Cloud認定資格 Professional Cloud DevOps Engineer", "sort_order": 27},
    {"name": "Google Cloud認定資格 Professional Cloud Security Engineer", "sort_order": 28},
    {"name": "Google Cloud認定資格 Professional Cloud Network Engineer", "sort_order": 29},
    {"name": "Google Cloud認定資格 Professional Google Workspace Administrator", "sort_order": 30},
    {
        "name": "Google Cloud認定資格 Professional Google Professional Machine Learning Engineer",
        "sort_order": 31,
    },
    {"name": "ITIL認定資格［ITIL］_Master", "sort_order": 32},
    {"name": "ITIL認定資格［ITIL］_Expert", "sort_order": 33},
    {"name": "ITIL認定資格［ITIL］_Intermediate", "sort_order": 34},
    {"name": "ITIL認定資格［ITIL］_Foundation", "sort_order": 35},
    {"name": "OMG認定UML技術者_アドバンスト", "sort_order": 36},
    {"name": "OMG認定UML技術者_インターメディエイト", "sort_order": 37},
    {"name": "OMG認定UML技術者_ファンダメンタル", "sort_order": 38},
    {"name": "UMTP認定UMLモデリング技能認定_L3", "sort_order": 39},
    {"name": "UMTP認定UMLモデリング技能認定_L2", "sort_order": 40},
    {"name": "UMTP認定UMLモデリング技能認定_L1", "sort_order": 41},
    {"name": "XML技術者認定_プロフェッショナル（データベース）", "sort_order": 42},
    {"name": "XML技術者認定_プロフェッショナル（アプリケーション開発）", "sort_order": 43},
    {"name": "XML技術者認定_ベーシック", "sort_order": 44},
    {"name": "CompTIA_IT Fundamentals", "sort_order": 45},
    {"name": "CompTIA_A+", "sort_order": 46},
    {"name": "CompTIA_NetWork+", "sort_order": 47},
    {"name": "CompTIA_Security+", "sort_order": 48},
    {"name": "CompTIA_Cloud+", "sort_order": 49},
    {"name": "CompTIA_Linux+", "sort_order": 50},
    {"name": "CompTIA_Server+", "sort_order": 51},
    {"name": "CompTIA_Advanced Security Practitioner (CASP+)", "sort_order": 52},
    {"name": "CompTIA_CyberSecurity Analyst+ (CySA+)", "sort_order": 53},
    {"name": "CompTIA_PenTest+", "sort_order": 54},
    {"name": "CompTIA_Data+", "sort_order": 55},
    {"name": "CompTIA_DataSys+", "sort_order": 56},
    {"name": "CompTIA_Project+", "sort_order": 57},
    {"name": "CompTIA_Cloud Essentials+", "sort_order": 58},
    {"name": "PHP技術者認定試験_上級", "sort_order": 59},
    {"name": "PHP技術者認定試験_初級", "sort_order": 60},
    {"name": "Androidプラットフォーム技術者認定試験_ベーシック", "sort_order": 61},
    {"name": "Androidアプリケーション技術者認定試験_ベーシック", "sort_order": 62},
    {"name": "アジャイルソフトウエア開発技術者検定試験_Lv1試験", "sort_order": 63},
    {"name": "アジャイルソフトウエア開発技術者検定試験_Lv2試験", "sort_order": 64},
    {"name": "Cisco認定資格_CCIE", "sort_order": 65},
    {"name": "Cisco認定資格_CCNP", "sort_order": 66},
    {"name": "Cisco認定資格_CCDA", "sort_order": 67},
    {"name": "Cisco認定資格_CCNA", "sort_order": 68},
    {"name": "LPIC(Linux Professional Institute Certification)_Level3（上級）", "sort_order": 69},
    {"name": "LPIC(Linux Professional Institute Certification)_Level2（中級）", "sort_order": 70},
    {"name": "LPIC(Linux Professional Institute Certification)_Level1（基礎）", "sort_order": 71},
    {"name": "Red Hat認定エンジニア", "sort_order": 72},
    {"name": "JSTQB認定テスト技術者資格_Advanced Level", "sort_order": 73},
    {"name": "JSTQB認定テスト技術者資格_Foundation Level", "sort_order": 74},
    {"name": "Vmware_VMware Certified Implementation Expert", "sort_order": 75},
    {"name": "Vmware_VMware Certified Professional", "sort_order": 76},
    {"name": "Vmware_VMware Certified Associate", "sort_order": 77},
    {"name": "LinuC(Linux Professional Certification)_Level3（上級）", "sort_order": 78},
    {"name": "LinuC(Linux Professional Certification)_Level2（中級）", "sort_order": 79},
    {"name": "LinuC(Linux Professional Certification)_Level1（基礎）", "sort_order": 80},
    {"name": "JDLA Deep Learning_G検定（JDLA Deep Learning for GENERAL）", "sort_order": 81},
    {"name": "JDLA Deep Learning_E資格（JDLA Deep Learning for ENGINEER）", "sort_order": 82},
    {"name": "VBAエキスパート_Excel VBAベーシック", "sort_order": 83},
    {"name": "VBAエキスパート_Excel VBAスタンダード", "sort_order": 84},
    {"name": "VBAエキスパート_Access VBAベーシック", "sort_order": 85},
    {"name": "VBAエキスパート_Access VBAスタンダード", "sort_order": 86},
    {"name": "AWS認定試験_ソリューションアーキテクト – アソシエイト", "sort_order": 87},
    {"name": "AWS認定試験_ソリューションアーキテクト – プロフェッショナル", "sort_order": 88},
    {"name": "AWS認定試験_デベロッパー – アソシエイト", "sort_order": 89},
    {"name": "AWS認定試験_SysOpsアドミニストレーター – アソシエイト", "sort_order": 90},
    {"name": "AWS認定試験_DevOps エンジニア – プロフェッショナル", "sort_order": 91},
    {"name": "AWS認定試験_AWS 認定クラウドプラクティショナー", "sort_order": 92},
    {"name": "HTML5_プロフェッショナル 認定試験 レベル1", "sort_order": 93},
    {"name": "HTML5_プロフェッショナル 認定試験 レベル2", "sort_order": 94},
    {"name": "OSS-DB_Silver", "sort_order": 95},
    {"name": "OSS-DB_Gold", "sort_order": 96},
    {"name": "OSS-DB_Platinum", "sort_order": 97},
    {"name": "RPA技術者検定_アソシエイト", "sort_order": 98},
    {"name": "RPA技術者検定_エキスパート", "sort_order": 99},
    {"name": "PythonED_Python3エンジニア認定基礎試験", "sort_order": 100},
    {"name": "PythonED_Python3エンジニア認定データ分析試験", "sort_order": 101},
    {"name": "Ruby技術者認定資格_Silver", "sort_order": 102},
    {"name": "Ruby技術者認定資格_Gold", "sort_order": 103},
    {"name": "Professional Scrum Master™_レベルⅢ（PSMⅢ）", "sort_order": 104},
    {"name": "Professional Scrum Master™_レベルⅡ（PSMⅡ）", "sort_order": 105},
    {"name": "Professional Scrum Master™_レベルI（PSM I）", "sort_order": 106},
    {"name": "モバイルシステム技術検定_シニアモバイルシステムコンサルタント", "sort_order": 107},
    {"name": "モバイルシステム技術検定_モバイルシステム技術検定試験 1級", "sort_order": 108},
    {"name": "モバイルシステム技術検定_モバイルシステム技術検定試験 2級", "sort_order": 109},
    {"name": "モバイルシステム技術検定_モバイル技術基礎検定", "sort_order": 110},
    {"name": "Microsoft認定資格_Azure Fundamentals", "sort_order": 111},
    {"name": "Microsoft認定資格_Azure AI Fundamentals", "sort_order": 112},
    {"name": "Microsoft認定資格_Azure Data Fundamentals", "sort_order": 113},
    {"name": "Microsoft認定資格_Microsoft 365 Fundamentals", "sort_order": 114},
    {"name": "Microsoft認定資格_Dynamics 365 Fundamentals(CRM)", "sort_order": 115},
    {"name": "Microsoft認定資格_Dynamics 365 Fundamentals(ERP)", "sort_order": 116},
    {"name": "Microsoft認定資格_Power Platform Fundamentals", "sort_order": 117},
    {
        "name": "Microsoft認定資格_Security, Compliance, and Identity Fundamentals",
        "sort_order": 118,
    },
    {"name": "Microsoft認定資格_Azure Administrator Associate", "sort_order": 119},
    {"name": "Microsoft認定資格_Azure Solutions Architect Expert", "sort_order": 120},
    {"name": "Microsoft認定資格_Azure Network Engineer Associate", "sort_order": 121},
    {"name": "Microsoft認定資格_Windows Server Hybrid Administrator Associate", "sort_order": 122},
    {"name": "Microsoft認定資格_Azure AI Engineer Associate", "sort_order": 123},
    {"name": "Microsoft認定資格_Power BI Data Analyst Associate", "sort_order": 124},
    {"name": "Microsoft認定資格_Azure Data Scientist Associate", "sort_order": 125},
    {"name": "Microsoft認定資格_Azure Data Engineer Associate", "sort_order": 126},
    {"name": "Microsoft認定資格_Azure Database Administrator Associate", "sort_order": 127},
    {"name": "Microsoft認定資格_Fabric Analytics Engineer Associate", "sort_order": 128},
    {"name": "Microsoft認定資格_Azure Developer Associate", "sort_order": 129},
    {"name": "Microsoft認定資格_DevOps Engineer Expert", "sort_order": 130},
    {"name": "Microsoft認定資格_Endpoint Administrator Associate", "sort_order": 131},
    {"name": "Microsoft認定資格_Administrator Expert", "sort_order": 132},
    {
        "name": "Microsoft認定資格_Collaboration Communication Systems Engineer Associate",
        "sort_order": 133,
    },
    {"name": "Microsoft認定資格_Teams Administrator Associate", "sort_order": 134},
    {
        "name": "Microsoft認定資格_Dynamics 365 Sales Functional Consultant Associate",
        "sort_order": 135,
    },
    {
        "name": "Microsoft認定資格_Dynamics 365 Customer Service Functional Consultant Associate",
        "sort_order": 136,
    },
    {
        "name": "Microsoft認定資格_Dynamics 365:Finance and Operations Apps Solution Architect Expert",
        "sort_order": 137,
    },
    {
        "name": "Microsoft認定資格_Dynamics 365:Field Service Functional Consultant Associate",
        "sort_order": 138,
    },
    {
        "name": "Microsoft認定資格_Dynamics 365 Finance Functional Consultant Associate",
        "sort_order": 139,
    },
    {
        "name": "Microsoft認定資格_Dynamics 365 Supply Chain Management Functional Consultant Associate",
        "sort_order": 140,
    },
    {
        "name": "Microsoft認定資格_Dynamics 365:Supply Chain Management Functional Consultant Expert",
        "sort_order": 141,
    },
    {
        "name": "Microsoft認定資格_Dynamics 365:Finance and Operations Apps Developer Associate",
        "sort_order": 142,
    },
    {
        "name": "Microsoft認定資格_Dynamics 365 Business Central Functional Consultant Associate",
        "sort_order": 143,
    },
    {
        "name": "Microsoft認定資格_Dynamics 365 Business Central Developer   Associate",
        "sort_order": 144,
    },
    {"name": "Microsoft認定資格_Power Platform Functional Consultant Associate", "sort_order": 145},
    {"name": "Microsoft認定資格_Power Platform Developer Associate", "sort_order": 146},
    {"name": "Microsoft認定資格_Power Automate RPA Developer Associate", "sort_order": 147},
    {"name": "Microsoft認定資格_Power Platform Solution Architect Expert", "sort_order": 148},
    {"name": "Microsoft認定資格_Azure Security Engineer Associate", "sort_order": 149},
    {"name": "Microsoft認定資格_Cybersecurity Architect Expert", "sort_order": 150},
    {"name": "Microsoft認定資格_Security Operations Analyst Associate", "sort_order": 151},
    {"name": "Microsoft認定資格_Identity and Access Administrator Associate", "sort_order": 152},
    {
        "name": "Microsoft認定資格_Information Protection and Compliance Administrator Associate",
        "sort_order": 153,
    },
    {"name": "Microsoft認定資格_Azure for SAP Workloads Specialty", "sort_order": 154},
    {"name": "Microsoft認定資格_Azure Virtual Desktop Specialty", "sort_order": 155},
    {"name": "Microsoft認定資格_Azure Cosmos DB Developers Specialty", "sort_order": 156},
    {"name": "Microsoft認定資格_Dynamics 365 Customer Insights(Data) Specialty", "sort_order": 157},
    {"name": "Oracle認定試験_ORACLE MASTER Bronze DBA 2019", "sort_order": 158},
    {"name": "Oracle認定試験_ORACLE MASTER Silver DBA 2019", "sort_order": 159},
    {"name": "Oracle認定試験_ORACLE MASTER Gold DBA 2019", "sort_order": 160},
    {"name": "Oracle認定試験_ORACLE MASTER Platinum DBA 2019", "sort_order": 161},
    {"name": "Oracle認定試験_ORACLE MASTER Silver SQL 2019", "sort_order": 162},
    {"name": "Oracle認定試験_ORACLE MASTER Bronze Oracle Database 12c", "sort_order": 163},
    {"name": "Oracle認定試験_ORACLE MASTER Silver Oracle Database 12c", "sort_order": 164},
    {"name": "Oracle認定試験_ORACLE MASTER Gold Oracle Database 12c", "sort_order": 165},
    {"name": "Oracle認定試験_ORACLE MASTER Platinum Oracle Database 12c", "sort_order": 166},
    {
        "name": "Oracle認定試験_ORACLE Certified Expert, Oracle Database 12c:RAC and Grid Infrastructure Administrator",
        "sort_order": 167,
    },
    {"name": "Oracle認定試験_MySQL 2021 Certified Implementation Specialist", "sort_order": 168},
    {
        "name": "Oracle認定試験_MySQL HeatWave Implementation Certified Associate Rel 1",
        "sort_order": 169,
    },
    {"name": "Oracle認定試験_Oracle Certified Java Programmer, Bronze SE", "sort_order": 170},
    {"name": "Oracle認定試験_Oracle Certified Java Programmer, Silver SE 11", "sort_order": 171},
    {"name": "Oracle認定試験_Oracle Certified Java Programmer, Gold SE 11", "sort_order": 172},
    {"name": "Oracle認定試験_Oracle Certified Java Programmer, Silver SE 17", "sort_order": 173},
    {"name": "Oracle認定試験_Oracle Certified Java Programmer, Gold SE 17", "sort_order": 174},
    {
        "name": "Oracle認定試験_Oracle Cloud Infrastructure 2023 AI Certified Foundations Associate",
        "sort_order": 175,
    },
    {
        "name": "Oracle認定試験_Oracle Cloud Infrastructure 2023 Certified Architect Associate",
        "sort_order": 176,
    },
    {
        "name": "Oracle認定試験_Oracle Cloud Infrastructure 2023 Certified Architect Professional",
        "sort_order": 177,
    },
    {
        "name": "Oracle認定試験_Oracle Cloud Infrastructure 2023 Certified Cloud Operations Professional",
        "sort_order": 178,
    },
    {
        "name": "Oracle認定試験_Oracle Cloud Infrastructure 2023 Certified Developer Professional",
        "sort_order": 179,
    },
    {
        "name": "Oracle認定試験_Oracle Cloud Infrastructure 2023 Certified Foundations Associate",
        "sort_order": 180,
    },
    {
        "name": "Oracle認定試験_Oracle Cloud Infrastructure 2023 Certified Security Professional",
        "sort_order": 181,
    },
    {
        "name": "Oracle認定試験_Data Management Oracle Autonomous Database Cloud 2023 Certified Professional",
        "sort_order": 182,
    },
    {
        "name": "Oracle認定試験_Data Management Oracle Base Database Services 2023 Certified Professional",
        "sort_order": 183,
    },
    {
        "name": "Oracle認定試験_Data Management Oracle Cloud Data Management 2023 Foundations Certified Associate",
        "sort_order": 184,
    },
    {
        "name": "Oracle認定試験_Data Management Oracle Database Cloud Administrator 2023 Certified Professional",
        "sort_order": 185,
    },
    {
        "name": "Oracle認定試験_Management Cloud Oracle Cloud Database 2023 Migration and Integration Certified Professional",
        "sort_order": 186,
    },
    {
        "name": "Oracle認定試験_Oracle Planning 2023 Certified Implementation Professional",
        "sort_order": 187,
    },
    {
        "name": "Oracle認定試験_Oracle Financials Cloud: General Ledger 2023 Certified Implementation Professional",
        "sort_order": 188,
    },
    {
        "name": "Oracle認定試験_Oracle Financials Cloud: Payables 2023 Certified Implementation Professional",
        "sort_order": 189,
    },
    {
        "name": "Oracle認定試験_Oracle Financials Cloud: Receivables 2023 Certified Implementation Professional",
        "sort_order": 190,
    },
    {
        "name": "Oracle認定試験_Oracle Inventory Cloud 2023 Certified Implementation Professional",
        "sort_order": 191,
    },
    {
        "name": "Oracle認定試験_Oracle Manufacturing Cloud 2023 Certified Implementation Professional",
        "sort_order": 192,
    },
    {
        "name": "Oracle認定試験_Oracle Order Management Cloud Order to Cash 2023 Certified Implementation Professional",
        "sort_order": 193,
    },
    {
        "name": "Oracle認定試験_Oracle Fusion Cloud Procurement 2023 Certified Implementation Professional",
        "sort_order": 194,
    },
    {"name": "日商簿記検定_1級", "sort_order": 195},
    {"name": "日商簿記検定_2級", "sort_order": 196},
    {"name": "日商ビジネス英語検定_1級", "sort_order": 197},
    {"name": "日商ビジネス英語検定_2級", "sort_order": 198},
    {"name": "日商ビジネス英語検定_3級", "sort_order": 199},
    {"name": "ファイナンシャルプランナー_1級", "sort_order": 200},
    {"name": "ファイナンシャルプランナー_2級", "sort_order": 201},
    {"name": "ファイナンシャルプランナー_3級", "sort_order": 202},
    {"name": "デリバティブ_3級", "sort_order": 203},
    {"name": "金融商品取引_3級", "sort_order": 204},
    {"name": "統計検定_1級", "sort_order": 205},
    {"name": "統計検定_準1級", "sort_order": 206},
    {"name": "統計検定_2級", "sort_order": 207},
    {"name": "統計検定_3級", "sort_order": 208},
    {"name": "統計検定_ 統計調査士", "sort_order": 209},
    {"name": "統計検定_ 専門統計調査士", "sort_order": 210},
    {"name": "統計検定_ データサイエンス基礎", "sort_order": 211},
    {"name": "統計検定_ データサイエンス発展", "sort_order": 212},
    {"name": "統計検定_ データサイエンスエキスパート", "sort_order": 213},
    {"name": "医療情報基礎知識検定", "sort_order": 214},
    {"name": "ビジネス実務法務検定_1級", "sort_order": 215},
    {"name": "ビジネス実務法務検定_2級", "sort_order": 216},
    {"name": "ビジネス実務法務検定_3級", "sort_order": 217},
    {"name": "給与計算実務能力検定_1級", "sort_order": 218},
    {"name": "給与計算実務能力検定_2級", "sort_order": 219},
    {"name": "マーケティング検定_1級", "sort_order": 220},
    {"name": "マーケティング検定_2級", "sort_order": 221},
    {"name": "マーケティング検定_3級", "sort_order": 222},
    {"name": "メンタルヘルス・マネジメント検定_Ⅰ種（マスターコース）", "sort_order": 223},
    {"name": "メンタルヘルス・マネジメント検定_Ⅱ種（ラインケアコース）", "sort_order": 224},
    {"name": "メンタルヘルス・マネジメント検定_Ⅲ種（セルフケアコース）", "sort_order": 225},
    {"name": "Salesforce 認定資格_アソシエイト", "sort_order": 226},
    {"name": "Salesforce 認定資格_アドミニストレーター", "sort_order": 227},
    {"name": "Salesforce 認定資格_Platform アプリケーションビルダー", "sort_order": 228},
    {"name": "Salesforce 認定資格_上級アドミニストレーター", "sort_order": 229},
    {"name": "Salesforce 認定資格_Data Cloudコンサルタント", "sort_order": 230},
    {"name": "Salesforce 認定資格_Sales Cloudコンサルタント", "sort_order": 231},
    {"name": "Salesforce 認定資格_Service Cloudコンサルタント", "sort_order": 232},
    {"name": "Salesforce 認定資格_Field Serviceコンサルタント", "sort_order": 233},
    {"name": "Salesforce 認定資格_Experience Cloudコンサルタント", "sort_order": 234},
    {"name": "Salesforce 認定資格_Platformデベロッパー", "sort_order": 235},
    {"name": "Salesforce 認定資格_上級Platformデベロッパー", "sort_order": 236},
    {
        "name": "Adobe Certified Professional_Visual Design using Adobe Photoshop 2023",
        "sort_order": 237,
    },
    {
        "name": "Adobe Certified Professional_Graphic Design & Illustration using Adobe Illustrator 2023",
        "sort_order": 238,
    },
    {
        "name": "Adobe Certified Professional_Digital Video using Adobe Premiere Pro 2023",
        "sort_order": 239,
    },
    {"name": "リテールマーケティング（販売士）_1級", "sort_order": 240},
    {"name": "リテールマーケティング（販売士）_2級", "sort_order": 241},
    {"name": "リテールマーケティング（販売士）_3級", "sort_order": 242},
    {"name": "コンタクトセンター検定_エントリー資格", "sort_order": 243},
    {"name": "コンタクトセンター検定_オペレーター資格", "sort_order": 244},
    {"name": "コンタクトセンター検定_スーパーバイザー資格", "sort_order": 245},
    {"name": "コンタクトセンター検定_オペレーションマネジメント資格", "sort_order": 246},
    {"name": "コンタクトセンター検定_コンタクトセンターアーキテクチャ資格", "sort_order": 247},
    {"name": "データ分析実務スキル検定_プロジェクトマネージャー級", "sort_order": 248},
    {"name": "プロジェクトマネジメント・プロフェッショナル(PMP)", "sort_order": 249},
]

# 技術スタックマスタ（カテゴリ付き）
_TECHNOLOGY_STACKS = [
    # --- バックエンド ---
    {"category": "language", "name": "Python", "sort_order": 1},
    {"category": "language", "name": "Java", "sort_order": 2},
    {"category": "language", "name": "Go", "sort_order": 3},
    {"category": "language", "name": "Ruby", "sort_order": 4},
    {"category": "language", "name": "PHP", "sort_order": 5},
    {"category": "language", "name": "Rust", "sort_order": 6},
    {"category": "language", "name": "Scala", "sort_order": 7},
    {"category": "language", "name": "Perl", "sort_order": 8},
    {"category": "language", "name": "Groovy", "sort_order": 9},
    {"category": "language", "name": "Erlang", "sort_order": 10},
    {"category": "language", "name": "Elixir", "sort_order": 11},
    # --- フロントエンド ---
    {"category": "language", "name": "JavaScript", "sort_order": 12},
    {"category": "language", "name": "TypeScript", "sort_order": 13},
    {"category": "language", "name": "HTML", "sort_order": 14},
    {"category": "language", "name": "CSS", "sort_order": 15},
    # --- モバイル ---
    {"category": "language", "name": "Kotlin", "sort_order": 16},
    {"category": "language", "name": "Swift", "sort_order": 17},
    {"category": "language", "name": "Dart", "sort_order": 18},
    {"category": "language", "name": "Objective-C", "sort_order": 19},
    # --- システム / 組み込み ---
    {"category": "language", "name": "C", "sort_order": 20},
    {"category": "language", "name": "C++", "sort_order": 21},
    {"category": "language", "name": "C#", "sort_order": 22},
    {"category": "language", "name": "Visual Basic", "sort_order": 23},
    {"category": "language", "name": "Fortran", "sort_order": 24},
    {"category": "language", "name": "Lua", "sort_order": 25},
    # --- データ / スクリプト ---
    {"category": "language", "name": "SQL", "sort_order": 26},
    {"category": "language", "name": "R", "sort_order": 27},
    {"category": "language", "name": "Julia", "sort_order": 28},
    {"category": "language", "name": "Shell", "sort_order": 29},
    # --- 関数型 / その他 ---
    {"category": "language", "name": "Haskell", "sort_order": 30},
    {"category": "language", "name": "F#", "sort_order": 31},
    {"category": "language", "name": "Lisp", "sort_order": 32},
    # --- フロントエンド (JS/TS) ---
    {"category": "framework", "name": "React", "sort_order": 33},
    {"category": "framework", "name": "Vue.js", "sort_order": 34},
    {"category": "framework", "name": "Angular", "sort_order": 35},
    {"category": "framework", "name": "Next.js", "sort_order": 36},
    {"category": "framework", "name": "Nuxt.js", "sort_order": 37},
    {"category": "framework", "name": "Svelte", "sort_order": 38},
    {"category": "framework", "name": "jQuery", "sort_order": 39},
    # --- バックエンド (JS/TS) ---
    {"category": "framework", "name": "Express", "sort_order": 40},
    {"category": "framework", "name": "NestJS", "sort_order": 41},
    {"category": "framework", "name": "Meteor", "sort_order": 42},
    # --- Python ---
    {"category": "framework", "name": "FastAPI", "sort_order": 43},
    {"category": "framework", "name": "Django", "sort_order": 44},
    {"category": "framework", "name": "Flask", "sort_order": 45},
    {"category": "framework", "name": "Tornado", "sort_order": 46},
    # --- Java ---
    {"category": "framework", "name": "Spring Boot", "sort_order": 47},
    {"category": "framework", "name": "Spring Framework", "sort_order": 48},
    {"category": "framework", "name": "Struts", "sort_order": 49},
    {"category": "framework", "name": "Play Framework", "sort_order": 50},
    # --- Ruby ---
    {"category": "framework", "name": "Ruby on Rails", "sort_order": 51},
    {"category": "framework", "name": "Sinatra", "sort_order": 52},
    # --- PHP ---
    {"category": "framework", "name": "Laravel", "sort_order": 53},
    {"category": "framework", "name": "Symfony", "sort_order": 54},
    {"category": "framework", "name": "CodeIgniter", "sort_order": 55},
    {"category": "framework", "name": "CakePHP", "sort_order": 56},
    {"category": "framework", "name": "Yii", "sort_order": 57},
    # --- Go ---
    {"category": "framework", "name": "Gin", "sort_order": 58},
    {"category": "framework", "name": "Echo", "sort_order": 59},
    {"category": "framework", "name": "Beego", "sort_order": 60},
    # --- Rust ---
    {"category": "framework", "name": "Actix-web", "sort_order": 61},
    {"category": "framework", "name": "Rocket", "sort_order": 62},
    # --- C# / .NET ---
    {"category": "framework", "name": ".NET", "sort_order": 63},
    {"category": "framework", "name": "ASP.NET", "sort_order": 64},
    {"category": "framework", "name": "Xamarin", "sort_order": 65},
    {"category": "framework", "name": "Unity", "sort_order": 66},
    # --- Kotlin ---
    {"category": "framework", "name": "Ktor", "sort_order": 67},
    {"category": "framework", "name": "Quarkus", "sort_order": 68},
    # --- Swift ---
    {"category": "framework", "name": "SwiftUI", "sort_order": 69},
    {"category": "framework", "name": "Vapor", "sort_order": 70},
    # --- モバイル ---
    {"category": "framework", "name": "Flutter", "sort_order": 71},
    {"category": "framework", "name": "React Native", "sort_order": 72},
    {"category": "os", "name": "Linux", "sort_order": 73},
    {"category": "os", "name": "Windows Server", "sort_order": 74},
    {"category": "os", "name": "macOS", "sort_order": 75},
    {"category": "os", "name": "iOS", "sort_order": 76},
    {"category": "os", "name": "Android", "sort_order": 77},
    {"category": "os", "name": "ChromeOS", "sort_order": 78},
    # --- RDB ---
    {"category": "db", "name": "PostgreSQL", "sort_order": 79},
    {"category": "db", "name": "MySQL", "sort_order": 80},
    {"category": "db", "name": "MariaDB", "sort_order": 81},
    {"category": "db", "name": "SQLite", "sort_order": 82},
    {"category": "db", "name": "Oracle Database", "sort_order": 83},
    {"category": "db", "name": "SQL Server", "sort_order": 84},
    {"category": "db", "name": "Amazon Aurora", "sort_order": 85},
    # --- NoSQL (ドキュメント / カラム) ---
    {"category": "db", "name": "MongoDB", "sort_order": 86},
    {"category": "db", "name": "Cassandra", "sort_order": 87},
    {"category": "db", "name": "Apache HBase", "sort_order": 88},
    {"category": "db", "name": "Firebase Realtime Database", "sort_order": 89},
    {"category": "db", "name": "Firebase Firestore", "sort_order": 90},
    # --- NoSQL (KVS / キャッシュ) ---
    {"category": "db", "name": "Redis", "sort_order": 91},
    {"category": "db", "name": "DynamoDB", "sort_order": 92},
    {"category": "db", "name": "Memcached", "sort_order": 93},
    # --- クラウドプロバイダー ---
    {"category": "cloud_provider", "name": "AWS", "sort_order": 94},
    {"category": "cloud_provider", "name": "Google Cloud", "sort_order": 95},
    {"category": "cloud_provider", "name": "Azure", "sort_order": 96},
    # --- コンテナ ---
    {"category": "container", "name": "Docker", "sort_order": 97},
    {"category": "container", "name": "Kubernetes", "sort_order": 98},
    # --- IaC ---
    {"category": "iac", "name": "Terraform", "sort_order": 99},
    {"category": "iac", "name": "Ansible", "sort_order": 100},
    {"category": "iac", "name": "cloudFormation", "sort_order": 101},
    # --- バージョン管理 ---
    {"category": "vcs", "name": "Git", "sort_order": 102},
    {"category": "vcs", "name": "GitHub", "sort_order": 103},
    {"category": "vcs", "name": "GitLab", "sort_order": 104},
    {"category": "vcs", "name": "SVN", "sort_order": 105},
    # --- CI/CD ---
    {"category": "ci_cd", "name": "Jenkins", "sort_order": 106},
    {"category": "ci_cd", "name": "CircleCI", "sort_order": 107},
    {"category": "ci_cd", "name": "GitHub Actions", "sort_order": 108},
    # --- プロジェクトツール ---
    {"category": "project_tool", "name": "Jira", "sort_order": 109},
    {"category": "project_tool", "name": "Confluence", "sort_order": 110},
    {"category": "project_tool", "name": "Slack", "sort_order": 111},
    {"category": "project_tool", "name": "Teams", "sort_order": 112},
    {"category": "project_tool", "name": "Notion", "sort_order": 113},
    {"category": "project_tool", "name": "Trello", "sort_order": 114},
    {"category": "project_tool", "name": "figma", "sort_order": 115},
    {"category": "project_tool", "name": "Miro", "sort_order": 116},
    {"category": "project_tool", "name": "backlog", "sort_order": 117},
    # --- 監視・可観測性 ---
    {"category": "monitoring", "name": "Datadog", "sort_order": 118},
    {"category": "monitoring", "name": "Grafana", "sort_order": 119},
    {"category": "monitoring", "name": "Elasticsearch", "sort_order": 120},
    {"category": "monitoring", "name": "cloudWatch", "sort_order": 121},
    {"category": "monitoring", "name": "cloudMonitoring", "sort_order": 122},
    # --- ミドルウェア ---
    {"category": "middleware", "name": "Nginx", "sort_order": 121},
    {"category": "middleware", "name": "Apache", "sort_order": 122},
    {"category": "middleware", "name": "Hulft", "sort_order": 123},
    # --- AI agent ---
    {"category": "ai_agent", "name": "ChatGPT", "sort_order": 124},
    {"category": "ai_agent", "name": "Claude", "sort_order": 125},
    {"category": "ai_agent", "name": "Gemini", "sort_order": 126},
]

def seed_master_data(db: Session) -> None:
    """マスタデータの初期シードを投入する。各テーブルが空の場合のみ投入される。"""
    MQualificationRepository(db).seed_if_empty(_QUALIFICATIONS)
    MTechnologyStackRepository(db).seed_if_empty(_TECHNOLOGY_STACKS)
