"""Pydantic スキーマ。"""

from .auth import GitHubCallbackRequest, LoginRequest, RegisterRequest, TokenResponse, UserResponse
from .basic_info import BasicInfoCreate, BasicInfoResponse, BasicInfoUpdate, BasicQualification
from .blog import (
    BlogAccountCreate,
    BlogAccountResponse,
    BlogArticleResponse,
    BlogScoreArticleResponse,
    BlogScoreResponse,
    BlogSummaryArticle,
    BlogSummaryRequest,
    BlogSummaryResponse,
    BlogSyncResponse,
)
from .career_analysis import (
    ActionItem,
    CareerAnalysisGenerateRequest,
    CareerAnalysisResponse,
    CareerAnalysisResult,
    CareerPathItem,
    StrengthItem,
    TechStackItem,
    TechStackSection,
)
from .intelligence import (
    AnalysisResponse,
    AnalyzeRequest,
    CachedAnalysisResponse,
    PositionAdviceResponse,
    PositionScoresResponse,
    SkillActivityItem,
    SkillActivityResponse,
    SkillTimelinePoint,
)
from .master_data import (
    MasterItem,
    MasterItemCreate,
    MasterItemUpdate,
    TechStackMasterCreate,
    TechStackMasterItem,
    TechStackMasterUpdate,
)
from .resume import (
    Client,
    Experience,
    Project,
    ProjectTeam,
    ResumeCreate,
    ResumeResponse,
    ResumeUpdate,
    TeamMember,
    TechnologyStackItem,
)
from .rirekisho import (
    RirekishoCreate,
    RirekishoHistory,
    RirekishoResponse,
    RirekishoUpdate,
)

__all__ = [
    "ActionItem",
    "AnalysisResponse",
    "AnalyzeRequest",
    "BasicInfoCreate",
    "BasicInfoResponse",
    "BasicInfoUpdate",
    "BasicQualification",
    "BlogAccountCreate",
    "BlogAccountResponse",
    "BlogArticleResponse",
    "BlogScoreArticleResponse",
    "BlogScoreResponse",
    "BlogSummaryArticle",
    "BlogSummaryRequest",
    "BlogSummaryResponse",
    "BlogSyncResponse",
    "CachedAnalysisResponse",
    "CareerAnalysisGenerateRequest",
    "CareerAnalysisResponse",
    "CareerAnalysisResult",
    "CareerPathItem",
    "Client",
    "Experience",
    "GitHubCallbackRequest",
    "LoginRequest",
    "MasterItem",
    "MasterItemCreate",
    "MasterItemUpdate",
    "PositionAdviceResponse",
    "PositionScoresResponse",
    "Project",
    "ProjectTeam",
    "RegisterRequest",
    "ResumeCreate",
    "ResumeResponse",
    "ResumeUpdate",
    "RirekishoCreate",
    "RirekishoHistory",
    "RirekishoResponse",
    "RirekishoUpdate",
    "StrengthItem",
    "SkillActivityItem",
    "SkillActivityResponse",
    "SkillTimelinePoint",
    "TeamMember",
    "TechStackItem",
    "TechStackMasterCreate",
    "TechStackMasterItem",
    "TechStackMasterUpdate",
    "TechStackSection",
    "TechnologyStackItem",
    "TokenResponse",
    "UserResponse",
]
