"""マスタデータの初期シードを投入するモジュール。"""

from sqlalchemy.orm import Session

from .repositories import (
    MPrefectureRepository,
    MQualificationRepository,
    MTechnologyStackRepository,
)

# 資格マスタ
_QUALIFICATIONS = [
    {"name": "基本情報技術者試験", "sort_order": 1},
    {"name": "応用情報技術者試験", "sort_order": 2},
    {"name": "AWS Solutions Architect Associate", "sort_order": 3},
    {"name": "AWS Solutions Architect Professional", "sort_order": 4},
    {"name": "AWS Developer Associate", "sort_order": 5},
    {"name": "AWS SysOps Administrator", "sort_order": 6},
    {"name": "Google Cloud Professional Cloud Architect", "sort_order": 7},
    {"name": "LPIC-1", "sort_order": 8},
    {"name": "LPIC-2", "sort_order": 9},
    {"name": "LPIC-3", "sort_order": 10},
    {"name": "Oracle Certified Java Programmer Silver", "sort_order": 11},
    {"name": "Oracle Certified Java Programmer Gold", "sort_order": 12},
    {"name": "Oracle Master Bronze", "sort_order": 13},
    {"name": "Oracle Master Silver", "sort_order": 14},
    {"name": "情報セキュリティマネジメント試験", "sort_order": 15},
    {"name": "ネットワークスペシャリスト試験", "sort_order": 16},
    {"name": "データベーススペシャリスト試験", "sort_order": 17},
    {"name": "ITストラテジスト試験", "sort_order": 18},
    {"name": "システムアーキテクト試験", "sort_order": 19},
    {"name": "プロジェクトマネージャ試験", "sort_order": 20},
    {"name": "TOEIC", "sort_order": 21},
    {"name": "TOEFL", "sort_order": 22},
    {"name": "日商簿記2級", "sort_order": 23},
    {"name": "日商簿記3級", "sort_order": 24},
    {"name": "PMP", "sort_order": 25},
]

# 技術スタックマスタ（カテゴリ付き）
_TECHNOLOGY_STACKS = [
    # 言語
    {"category": "language", "name": "Python", "sort_order": 1},
    {"category": "language", "name": "JavaScript", "sort_order": 2},
    {"category": "language", "name": "TypeScript", "sort_order": 3},
    {"category": "language", "name": "Java", "sort_order": 4},
    {"category": "language", "name": "Go", "sort_order": 5},
    {"category": "language", "name": "Rust", "sort_order": 6},
    {"category": "language", "name": "C", "sort_order": 7},
    {"category": "language", "name": "C++", "sort_order": 8},
    {"category": "language", "name": "C#", "sort_order": 9},
    {"category": "language", "name": "Ruby", "sort_order": 10},
    {"category": "language", "name": "PHP", "sort_order": 11},
    {"category": "language", "name": "Kotlin", "sort_order": 12},
    {"category": "language", "name": "Swift", "sort_order": 13},
    {"category": "language", "name": "Scala", "sort_order": 14},
    {"category": "language", "name": "R", "sort_order": 15},
    {"category": "language", "name": "SQL", "sort_order": 16},
    {"category": "language", "name": "HTML", "sort_order": 17},
    {"category": "language", "name": "CSS", "sort_order": 18},
    {"category": "language", "name": "Bash", "sort_order": 19},
    # フレームワーク
    {"category": "framework", "name": "React", "sort_order": 20},
    {"category": "framework", "name": "Vue.js", "sort_order": 21},
    {"category": "framework", "name": "Angular", "sort_order": 22},
    {"category": "framework", "name": "Next.js", "sort_order": 23},
    {"category": "framework", "name": "Nuxt.js", "sort_order": 24},
    {"category": "framework", "name": "Express", "sort_order": 25},
    {"category": "framework", "name": "NestJS", "sort_order": 26},
    {"category": "framework", "name": "FastAPI", "sort_order": 27},
    {"category": "framework", "name": "Django", "sort_order": 28},
    {"category": "framework", "name": "Flask", "sort_order": 29},
    {"category": "framework", "name": "Spring Boot", "sort_order": 30},
    {"category": "framework", "name": "Ruby on Rails", "sort_order": 31},
    {"category": "framework", "name": "Laravel", "sort_order": 32},
    {"category": "framework", "name": ".NET", "sort_order": 33},
    # OS
    {"category": "os", "name": "Linux", "sort_order": 34},
    {"category": "os", "name": "Windows Server", "sort_order": 35},
    {"category": "os", "name": "macOS", "sort_order": 36},
    # DB
    {"category": "db", "name": "PostgreSQL", "sort_order": 37},
    {"category": "db", "name": "MySQL", "sort_order": 38},
    {"category": "db", "name": "SQLite", "sort_order": 39},
    {"category": "db", "name": "MongoDB", "sort_order": 40},
    {"category": "db", "name": "Redis", "sort_order": 41},
    {"category": "db", "name": "DynamoDB", "sort_order": 42},
    {"category": "db", "name": "Oracle Database", "sort_order": 43},
    {"category": "db", "name": "SQL Server", "sort_order": 44},
    # クラウドリソース
    {"category": "cloud_resource", "name": "AWS", "sort_order": 45},
    {"category": "cloud_resource", "name": "Google Cloud", "sort_order": 46},
    {"category": "cloud_resource", "name": "Azure", "sort_order": 47},
    {"category": "cloud_resource", "name": "Docker", "sort_order": 48},
    {"category": "cloud_resource", "name": "Kubernetes", "sort_order": 49},
    {"category": "cloud_resource", "name": "Terraform", "sort_order": 50},
    {"category": "cloud_resource", "name": "Ansible", "sort_order": 51},
    # 開発支援ツール
    {"category": "dev_tool", "name": "Git", "sort_order": 52},
    {"category": "dev_tool", "name": "GitHub", "sort_order": 53},
    {"category": "dev_tool", "name": "GitLab", "sort_order": 54},
    {"category": "dev_tool", "name": "Jenkins", "sort_order": 55},
    {"category": "dev_tool", "name": "CircleCI", "sort_order": 56},
    {"category": "dev_tool", "name": "GitHub Actions", "sort_order": 57},
    {"category": "dev_tool", "name": "Jira", "sort_order": 58},
    {"category": "dev_tool", "name": "Confluence", "sort_order": 59},
    {"category": "dev_tool", "name": "Slack", "sort_order": 60},
    {"category": "dev_tool", "name": "Datadog", "sort_order": 61},
    {"category": "dev_tool", "name": "Grafana", "sort_order": 62},
    {"category": "dev_tool", "name": "Elasticsearch", "sort_order": 63},
    {"category": "dev_tool", "name": "Nginx", "sort_order": 64},
    {"category": "dev_tool", "name": "Apache", "sort_order": 65},
]

# 都道府県マスタ（JIS X 0401 順）
_PREFECTURES = [
    {"name": "北海道", "sort_order": 1},
    {"name": "青森県", "sort_order": 2},
    {"name": "岩手県", "sort_order": 3},
    {"name": "宮城県", "sort_order": 4},
    {"name": "秋田県", "sort_order": 5},
    {"name": "山形県", "sort_order": 6},
    {"name": "福島県", "sort_order": 7},
    {"name": "茨城県", "sort_order": 8},
    {"name": "栃木県", "sort_order": 9},
    {"name": "群馬県", "sort_order": 10},
    {"name": "埼玉県", "sort_order": 11},
    {"name": "千葉県", "sort_order": 12},
    {"name": "東京都", "sort_order": 13},
    {"name": "神奈川県", "sort_order": 14},
    {"name": "新潟県", "sort_order": 15},
    {"name": "富山県", "sort_order": 16},
    {"name": "石川県", "sort_order": 17},
    {"name": "福井県", "sort_order": 18},
    {"name": "山梨県", "sort_order": 19},
    {"name": "長野県", "sort_order": 20},
    {"name": "岐阜県", "sort_order": 21},
    {"name": "静岡県", "sort_order": 22},
    {"name": "愛知県", "sort_order": 23},
    {"name": "三重県", "sort_order": 24},
    {"name": "滋賀県", "sort_order": 25},
    {"name": "京都府", "sort_order": 26},
    {"name": "大阪府", "sort_order": 27},
    {"name": "兵庫県", "sort_order": 28},
    {"name": "奈良県", "sort_order": 29},
    {"name": "和歌山県", "sort_order": 30},
    {"name": "鳥取県", "sort_order": 31},
    {"name": "島根県", "sort_order": 32},
    {"name": "岡山県", "sort_order": 33},
    {"name": "広島県", "sort_order": 34},
    {"name": "山口県", "sort_order": 35},
    {"name": "徳島県", "sort_order": 36},
    {"name": "香川県", "sort_order": 37},
    {"name": "愛媛県", "sort_order": 38},
    {"name": "高知県", "sort_order": 39},
    {"name": "福岡県", "sort_order": 40},
    {"name": "佐賀県", "sort_order": 41},
    {"name": "長崎県", "sort_order": 42},
    {"name": "熊本県", "sort_order": 43},
    {"name": "大分県", "sort_order": 44},
    {"name": "宮崎県", "sort_order": 45},
    {"name": "鹿児島県", "sort_order": 46},
    {"name": "沖縄県", "sort_order": 47},
]


def seed_master_data(db: Session) -> None:
    """マスタデータの初期シードを投入する。各テーブルが空の場合のみ投入される。"""
    MQualificationRepository(db).seed_if_empty(_QUALIFICATIONS)
    MTechnologyStackRepository(db).seed_if_empty(_TECHNOLOGY_STACKS)
    MPrefectureRepository(db).seed_if_empty(_PREFECTURES)
